/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-05-12 06:50:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ViewCapaianSatMan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1424146929100L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar", Long.valueOf(1427884006427L));
    _jspx_dependants.put("jar:file:/D:/AMANDA/COLLEGES/BISMILLAH/TA%20READY/TA%20TA%20TA%20112/PROGRAM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TAMVC/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/D:/AMANDA/COLLEGES/BISMILLAH/TA%20READY/TA%20TA%20TA%20112/PROGRAM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TAMVC/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1329377332000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fcommandName_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fhidden_0026_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fcommandName_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fhidden_0026_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fcommandName_005fclass.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fhidden_0026_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<link rel=\"shortcut icon\"\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/favicon_16.ico\">\r\n");
      out.write("\t<title>Modern | Layouts - Horizontal Menu</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Admin Dashboard Template\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"admin,dashboard\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"Steelcoders\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Styles -->\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600'\r\n");
      out.write("\t\trel='stylesheet' type='text/css'>\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/uniform/css/uniform.default.min.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/fontawesome/css/font-awesome.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/line-icons/simple-line-icons.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/waves/waves.min.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/switchery/switchery.min.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/3d-bold-navigation/css/style.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/slidepushmenus/css/component.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/toastr/toastr.min.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap-datepicker/css/datepicker3.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t<!-- Theme Styles -->\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/modern.min.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/themes/white.css\"\r\n");
      out.write("\t\tclass=\"theme-color\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/custom.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/3d-bold-navigation/js/modernizr.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/offcanvasmenueffects/js/snap.svg-min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery/jquery-2.1.3.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/toastr/toastr.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\t<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("\t        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("\t        <![endif]-->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar context_path = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<title>Datatable</title>\r\n");
      out.write("</head>\t\r\n");
      out.write("<body class=\"page-header-fixed page-horizontal-bar\">\r\n");
      out.write("\t<form class=\"search-form\" action=\"#\" method=\"GET\">\r\n");
      out.write("\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"search\" class=\"form-control search-input\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Search...\"> <span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-default close-search waves-effect waves-button waves-classic\"\r\n");
      out.write("\t\t\t\t\ttype=\"button\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Input Group -->\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<!-- Search Form -->\r\n");
      out.write("\t<main class=\"page-content content-wrap\">\r\n");
      out.write("\t<div class=\"navbar\">\r\n");
      out.write("\t\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-pusher\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\t\t\tclass=\"waves-effect waves-button waves-classic push-sidebar\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"logo-box\">\r\n");
      out.write("\t\t\t\t<a href=\"index.html\" class=\"logo-text\"><span>Modern</span></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Logo Box -->\r\n");
      out.write("\t\t\t<div class=\"search-button\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\t\t\tclass=\"waves-effect waves-button waves-classic show-search\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-search\"></i></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"topmenu-outer\">\r\n");
      out.write("\t\t\t\t<div class=\"top-menu\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-left\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"waves-effect waves-button waves-classic sidebar-toggle\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-bars\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"waves-effect waves-button waves-classic toggle-fullscreen\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-expand\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-toggle waves-effect waves-button waves-classic\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\"> <i class=\"fa fa-cogs\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-menu dropdown-md dropdown-list theme-settings\"\r\n");
      out.write("\t\t\t\t\t\t\t\trole=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"li-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"no-link\" role=\"presentation\">Fixed Header\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ios-switch pull-right switch-md\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"js-switch pull-right fixed-header-check\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"li-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"no-link\" role=\"presentation\">Fixed Sidebar\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ios-switch pull-right switch-md\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"js-switch pull-right fixed-sidebar-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"no-link\" role=\"presentation\">Horizontal bar\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ios-switch pull-right switch-md\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"js-switch pull-right horizontal-bar-check\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"no-link\" role=\"presentation\">Toggle Sidebar\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ios-switch pull-right switch-md\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"js-switch pull-right toggle-sidebar-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"no-link\" role=\"presentation\">Compact Menu\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ios-switch pull-right switch-md\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"js-switch pull-right compact-menu-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"no-link\" role=\"presentation\">Hover Menu\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ios-switch pull-right switch-md\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"js-switch pull-right hover-menu-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"li-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"no-link\" role=\"presentation\">Boxed Layout\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ios-switch pull-right switch-md\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"js-switch pull-right boxed-layout-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"no-link\"><button\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-default reset-options\">Reset Options</button></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"waves-effect waves-button waves-classic show-search\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-search\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-toggle waves-effect waves-button waves-classic\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\"> <span class=\"user-name\">David<i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-down\"></i></span> <img class=\"img-circle avatar\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/avatar1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\twidth=\"40\" height=\"40\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-list\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"profile.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-user\"></i>Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"calendar.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-calendar\"></i>Calendar</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"inbox.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-envelope\"></i>Inbox<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"badge badge-success pull-right\">4</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"lock-screen.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-lock\"></i>Lock screen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"login.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-sign-out m-r-xs\"></i>Log out</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.html\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"log-out waves-effect waves-button waves-classic\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-sign-out m-r-xs\"></i>Log out</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!-- Nav -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Top Menu -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Navbar -->\r\n");
      out.write("\t<div class=\"horizontal-bar sidebar\">\r\n");
      out.write("\t\t<div class=\"page-sidebar-inner slimscroll\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-header\">\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-profile\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" id=\"profile-menu-link\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-profile-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/avatar1.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-circle img-responsive\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebar-profile-details\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>David Green<br> <small>Art Director</small></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"menu accordion-menu\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\" class=\"waves-effect waves-button\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon glyphicon glyphicon-home\"></span>\r\n");
      out.write("\t\t\t\t\t\t<p>Dashboard</p></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"profile.html\" class=\"waves-effect waves-button\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon glyphicon glyphicon-user\"></span>\r\n");
      out.write("\t\t\t\t\t\t<p>Profile</p></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"droplink\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"waves-effect waves-button\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-icon glyphicon glyphicon-flash\"></span>\r\n");
      out.write("\t\t\t\t\t\t<p>Levels</p> <span class=\"arrow\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"droplink\"><a href=\"#\"><p>Level 1.1</p> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"arrow\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"droplink\"><a href=\"#\"><p>Level 2.1</p> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"arrow\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Level 3.1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Level 2.2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Level 1.2</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Page Sidebar Inner -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Page Sidebar --> <!-- Content -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"page-inner\">\r\n");
      out.write("\t\t<div class=\"page-title\">\r\n");
      out.write("\t\t\t<h3>Horizontal Menu</h3>\r\n");
      out.write("\t\t\t<div class=\"page-breadcrumb\">\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Layouts</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">Horizontal Menu</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"main-wrapper\">\r\n");
      out.write("\t\t<!-- akhir dari header -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Content -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t<link rel=\"stylesheet\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery.datatables/media/css/jquery.dataTables.min.css\">\r\n");
      out.write("\t\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery.datatables/media/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery.datatables/extensions/TableTools/css/dataTables.tableTools.min.css\">\r\n");
      out.write("\t\t\t<!-- optional -->\r\n");
      out.write("\t\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery.datatables/extensions/TableTools/js/dataTables.tableTools.min.js\"></script>\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery.datatables/extensions/ColVis/css/dataTables.colVis.min.css\">\r\n");
      out.write("\t\t\t<!-- optional -->\r\n");
      out.write("\t\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery.datatables/extensions/ColVis/js/dataTables.colVis.min.js\"></script>\r\n");
      out.write("\t\t\t<!-- optional -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<script\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery-validation/jquery.validate.min.js\"\r\n");
      out.write("\t\t\t\trel=\"stylesheet\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t\t<script\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery-blockui/jquery.blockui.js\"\r\n");
      out.write("\t\t\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t\t\t<script\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.masterpage.sia.js\"\r\n");
      out.write("\t\t\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/date.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t\t\t<div class=\"row\" id=\"masterpage\"> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\" style=\"margin-bottom:10px;\">\r\n");
      out.write("\t\t\t\t\t\t \t<div class=\"panel panel-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"panel-title\">Mata Kuliah</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Tabel menampilkan capaian pembelajaran</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>Status Aktif</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"filter\" name=\"filter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"false\">Aktif</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Semua</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8 masteractions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"btn-action pull-right\"> </div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"tableform\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"table table-striped table-bordered table-hover table-checkable table-colvis datatable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"checkbox-all\" type=\"checkbox\" id=\"flat-checkbox-1\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Tahun Kurikulum</td>   \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Nama Kurikulum</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Nama Satuan Manajemen</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Nama Capaian Induk</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Nama Capaian Utama</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Deskripsi Capaian</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Status Hapus</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Aksi</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-8 masteractions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-right\">  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-block\" onclick=\"location.href='/modul/matakuliah/rumpun/'\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  Selanjutnya >>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-right\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-block\" onclick=\"location.href='/modul/kurikulum/'\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t << Kembali\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\" id=\"master-detail\" style=\"display:none;\"> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"panel-title\">Capaian Belajar</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 id=\"title\">Capaian Belajar </h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<div id=\"myModal\" class=\"modal fade\">\r\n");
      out.write("\t\t\t\t  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("\t\t\t\t        <h4 class=\"modal-title\">Induk Capaian Pembelajaran</h4>\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t      \t<div id=\"masterpageCapPemb\" class =\"col-md-12\"> \r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"tableform\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table table-striped table-bordered table-hover table-checkable table-colvis datatable\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t#\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Tahun Kurikulum</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Nama Kurikulum</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Nama Satuan Manajemen</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Nama Capaian</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Deskripsi Capaian</td>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t      <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t    </div><!-- /.modal-content -->\r\n");
      out.write("\t\t\t\t  </div><!-- /.modal-dialog -->\r\n");
      out.write("\t\t\t\t</div><!-- /.modal -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Script Custom pada halaman. Kamu bisa memisah script pada file terpisah dengan menaruhnya di resource/js/namamodul/namafile.js -->\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tvar showModal;\r\n");
      out.write("\t\t\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\t\t$('#masterpage').masterPage(\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tdetailFocusId: '#idCapPemb',\r\n");
      out.write("\t\t\t\t\t\t\tdataUrl: context_path+'capaianbelajar/satuanmanajemen/json',\r\n");
      out.write("\t\t\t\t\t\t\tdetailUrl: context_path+'capaianbelajar/satuanmanajemen/edit',\r\n");
      out.write("\t\t\t\t\t\t\taddUrl: context_path+'capaianbelajar/satuanmanajemen/simpan',\r\n");
      out.write("\t\t\t\t\t\t\teditUrl: context_path+'capaianbelajar/satuanmanajemen/simpan',\r\n");
      out.write("\t\t\t\t\t\t\tdeleteUrl: context_path+'capaianbelajar/satuanmanajemen/deletemany',\r\n");
      out.write("\t\t\t\t\t\t\tprimaryKey: 'idCapPemb',\r\n");
      out.write("\t\t\t\t\t        order: [[3,\"asc\"]],\r\n");
      out.write("\t\t\t\t\t\t\teditOnClick: false,\r\n");
      out.write("\t\t\t\t\t\t\teditOnClickRow: true,\r\n");
      out.write("\t\t\t\t\t\t\tcols: [\r\n");
      out.write("\t\t\t\t\t\t\t\t/* id */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"bVisible\":    true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbSortable: false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmRender: function(data,type,full){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn '<input type=\"checkbox\" class=\"checkbox-data\" name=\"idCapPemb[]\" value=\"'+data+'\">';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t/* tahun kurikulum */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    false }, \r\n");
      out.write("\t\t\t\t\t\t\t\t/* nama kurikulum */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    true }, \r\n");
      out.write("\t\t\t\t\t\t\t\t/* Nama satuan manajemen */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    false }, \r\n");
      out.write("\t\t\t\t\t\t\t\t/* nama capaian induk */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    true },\r\n");
      out.write("\t\t\t\t\t\t\t\t/* nama capaian utama */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    true },\r\n");
      out.write("\t\t\t\t\t\t\t\t/* deskripsi capaian */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    false },\r\n");
      out.write("\t\t\t\t\t\t\t\t/*status hapus*/\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"bVisible\":    false, \r\n");
      out.write("\t\t\t\t\t\t\t\t\tmRender: function(data,type,full){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(full[7]=='false') return \"Aktif\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn \"Terhapus\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t/* Aksi */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"bVisible\":    true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbSortable: false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmRender: function(data,type,full){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar action = '<button type=\"button\" class=\"btn btn-primary editrow\">Edit</button>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(full[7]=='false') return action += ' <button type=\"button\" class=\"btn btn-danger deleterow\">Hapus</button>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn action;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\tvalidationRules: {idKurikulum:{required: true}, idSatMan:{required: true}, namaCapPemb:{required: true}},\r\n");
      out.write("\t\t\t\t\t\t\tfilters: [{id:'#filter', name:'statusHapusCapPemb'}],\r\n");
      out.write("\t\t\t\t\t\t\tcallOnFillForm : function(response,options){ \r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#idCapPemb\").val(response.data.idCapPemb);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#idKurikulum\").val(response.data.kurikulum.idKurikulum);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#idSatMan\").val(response.data.satMan.idSatMan); \r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tshowModal = function (){\r\n");
      out.write("\t\t\t\t\t\t\t$('#myModal').modal('show');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$('#myModal').on('shown.bs.modal', function (e) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#masterpageCapPemb\").find('.dataTables_length select').change();\r\n");
      out.write("\t\t\t\t\t\t\t  //if (!data) return e.preventDefault() // stops modal from being shown\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t$('#masterpageCapPemb').masterPage(\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tdetailFocusId: '#idIndukCapPemb',\r\n");
      out.write("\t\t\t\t\t\t\tdataUrl: context_path+'capaianbelajar/satuanmanajemen/subcapaian/json',\r\n");
      out.write("\t\t\t\t\t\t\tdetailUrl: context_path+'capaianbelajar/satuanmanajemen/subcapaian/edit',\r\n");
      out.write("\t\t\t\t\t\t\tprimaryKey: 'idCapPemb',\r\n");
      out.write("\t\t\t\t\t        order: [[3,\"asc\"]],\r\n");
      out.write("\t\t\t\t\t\t\teditOnClick: false,\r\n");
      out.write("\t\t\t\t\t\t\tdialogDetail: '',\r\n");
      out.write("\t\t\t\t\t\t\teditOnClickRow: true,\r\n");
      out.write("\t\t\t\t\t\t\tcols: [\r\n");
      out.write("\t\t\t\t\t\t\t\t/* id capaian pembelajaran */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"bVisible\":    true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbSortable: false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbSearchable: false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmRender: function(data,type,full){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn '<button type=\"button\" class=\"btn btn-primary\">Pilih</button>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t/* tahun kurikulum */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    false },\r\n");
      out.write("\t\t\t\t\t\t\t\t/* nama kurikulum  */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    true },\r\n");
      out.write("\t\t\t\t\t\t\t\t/* nama satuan manajemen */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    false },\r\n");
      out.write("\t\t\t\t\t\t\t\t/* nama capaian */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    true }, \r\n");
      out.write("\t\t\t\t\t\t\t\t/* deskripsi */\r\n");
      out.write("\t\t\t\t\t\t\t\t{ \"bVisible\":    false }, \r\n");
      out.write("\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\tcallOnSelect:function(aData, options){\r\n");
      out.write("// \t\t\t\t\t\t\t\t$(\"#parentCapPemb\").html(aData[4]);  \r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#parentCapPemb\").html(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<div class='alert alert-warning alert-dismissable'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+\"<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>x</button>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+\"<p>\"+aData[4]+\"<p>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+\"</div>\" \r\n");
      out.write("// \t\t\t\t\t\t\t\t\t\t+\"<input type='hidden' name='idIndukCapPemb[]' value='\"+ aData[0] +\"' />\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#idIndukCapPemb[]\").val(aData[0]);\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#myModal').modal('toggle');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<!-- akhir script custom pada halaman -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- akhir dari content content -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- footer -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Main Wrapper -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"page-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"no-s\">2015 &copy; Modern by Steelcoders.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Page Inner -->\r\n");
      out.write("\t\t\t\t\t\t<!--content-->\r\n");
      out.write("\t\t\t\t</main>\r\n");
      out.write("\t\t\t\t<!-- akhir dari content content -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Javascripts -->\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery-blockui/jquery.blockui.js\"></script>\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/switchery/switchery.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/uniform/jquery.uniform.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/waves/waves.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/3d-bold-navigation/js/main.js\"></script>\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/modern.js\"></script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fcommandName_005fclass.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/views/ViewCapaianSatMan.jsp(394,9) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "role", "form");
    // /WEB-INF/views/ViewCapaianSatMan.jsp(394,9) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setCommandName("capPemb");
    // /WEB-INF/views/ViewCapaianSatMan.jsp(394,9) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "formdetail");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Tahun Kurikulum</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<select id=\"idKurikulum\" name=\"idKurikulum\" class=\"form-control\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Pilih tahun dan nama kurikulum</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Nama Satuan Manajemen</label>\r\n");
          out.write("\t\t<!-- \t\t\t\t\t\t\t\t\tsetelah dia milih satuan manajemen yang mana, di trace induknya siapa buat ngedapetin capaian belajar dari induknya -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<select id=\"idSatMan\" name=\"idSatMan\" class=\"form-control\"> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Pilih nama satuan manajemen</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Induk Capaian Pembelajaran</label> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<br />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"showModal()\">Tambah induk capaian pembelajaran</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t <div id=\"parentCapPemb\"> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t \t<input type=\"hidden\" name=\"idIndukCapPemb[]\" ></input>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t </div> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Nama Capaian Belajar</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005fhidden_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<label>Deskripsi Capaian Belajar</label>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_form_005finput_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group detailcontrol\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fcommandName_005fclass.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/ViewCapaianSatMan.jsp(399,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ViewCapaianSatMan.jsp(399,12) '${kurikulumList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${kurikulumList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/ViewCapaianSatMan.jsp(399,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("kurikulum");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kurikulum.idKurikulum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kurikulum.thnMulai}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write('-');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kurikulum.namaKurikulum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/ViewCapaianSatMan.jsp(409,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/ViewCapaianSatMan.jsp(409,13) '${satManList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${satManList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/ViewCapaianSatMan.jsp(409,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("satman");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${satman.idSatMan}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${satman.nmSatMan }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/ViewCapaianSatMan.jsp(424,11) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setPath("namaCapPemb");
    // /WEB-INF/views/ViewCapaianSatMan.jsp(424,11) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/ViewCapaianSatMan.jsp(424,11) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "placeholder", "Berisi nama capaian pembelajaran");
    // /WEB-INF/views/ViewCapaianSatMan.jsp(424,11) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "required", "true");
    int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
      if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005frequired_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_form_005fhidden_005f0 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fform_005fhidden_0026_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    _jspx_th_form_005fhidden_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/ViewCapaianSatMan.jsp(425,11) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fhidden_005f0.setPath("idCapPemb");
    // /WEB-INF/views/ViewCapaianSatMan.jsp(425,11) null
    _jspx_th_form_005fhidden_005f0.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_form_005fhidden_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fhidden_005f0 = _jspx_th_form_005fhidden_005f0.doStartTag();
      if (_jspx_th_form_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fhidden_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fhidden_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fhidden_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fhidden_0026_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005fhidden_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/ViewCapaianSatMan.jsp(429,11) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setPath("deskripsiCapPemb");
    // /WEB-INF/views/ViewCapaianSatMan.jsp(429,11) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "class", "form-control");
    // /WEB-INF/views/ViewCapaianSatMan.jsp(429,11) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "placeholder", "Berisi deskripsi capaian pembelajaran");
    int[] _jspx_push_body_count_form_005finput_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f1 = _jspx_th_form_005finput_005f1.doStartTag();
      if (_jspx_th_form_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f1);
    }
    return false;
  }
}
